name: Setup Environment
description: Clones repo and installs compiler + tools

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
        g++-14 make valgrind libgtest-dev cmake

    - name: Set compiler to g++-14
      shell: bash
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        sudo update-alternatives --set g++ /usr/bin/g++-14
