name: CI

on:
  push:
    paths:
      - "**/*.cpp"
      - "**/*.hpp"
      - "include/**"
      - "src/**"
      - "tests/**"
      - "Makefile"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "**/*.cpp"
      - "**/*.hpp"
      - "include/**"
      - "src/**"
      - "tests/**"
      - "Makefile"
      - ".github/workflows/**"

jobs:
  compile:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build
        run: make -B

      - name: Upload the build artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: build/

  memory_test:
    name: Run memory test with valgrind
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Download the build artifact
        if: ${{ !env.ACT }}
        uses: actions/download-artifact@v4
        with:
          name: build_artifact

      - name: Local build artifact for act
        if: ${{ env.ACT }}
        run: make

      - name: Run valgrind test
        run: make valgrind

  unit_test:
    name: Run unit test with GTest
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Download the build artifact
        if: ${{ !env.ACT }}
        uses: actions/download-artifact@v4
        with:
          name: build_artifact

      - name: Local build artifact for act
        if: ${{ env.ACT }}
        run: make

      - name: Run unit test
        run: make test
