name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-14 make valgrind
          sudo apt-get install -y libgtest-dev cmake

      - name: Set compiler to g++-14
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          sudo update-alternatives --set g++ /usr/bin/g++-14

      - name: Build
        run: make -B

      - name: Run tests with Valgrind
        run: make valgrind
